apiVersion: v1
kind: Service
metadata:
  name: {{ include "titan.fullname" . }}
  labels:
    {{- include "titan.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: titan
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.ai.enabled }}
    - name: ai-http
      port: {{ .Values.ai.port }}
      targetPort: ai-http
    {{- end }}
