apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: titan-support-model
  namespace: titan-system
spec:
  predictor:
    containers:
      - name: kserve-container
        image: vllm/vllm-openai:v0.6.6.post1
        args: ["--model=Qwen/Qwen2.5-1.5B-Instruct", "--max-model-len=4096"]
        resources:
          limits: {nvidia.com/gpu: "1", memory: 20Gi}

