apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: titan-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GIT_REPOSITORY
    targetRevision: main
    path: platform/kubernetes/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: titan-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

